### ISSUE TITLE
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

### ISSUE THREAD

**Issue by tilaj** [zendframework/zend-mvc-i18n#23]
Is change planned to "psr/container"?

**Comment by Ocramius** [comment]
Changing to `psr/container` will happen, but since `container-interop/container-interop` extends that interface, and the change would be a major BC break (even without API changes), this is very very low on the priority list.

Please note that we abandoned the upstream `container-interop/container-interop` package, but it stays stable anyway.
